// Code generated by MockGen. DO NOT EDIT.
// Source: internal/deposit/shared/model.go

// Package zota is a generated GoMock package.
package zota

import (
	reflect "reflect"
	shared "zota-dev-challenge/internal/deposit/shared"

	gomock "github.com/golang/mock/gomock"
)

// MockDepositPaymentGateway is a mock of DepositPaymentGateway interface.
type MockDepositPaymentGateway struct {
	ctrl     *gomock.Controller
	recorder *MockDepositPaymentGatewayMockRecorder
}

// MockDepositPaymentGatewayMockRecorder is the mock recorder for MockDepositPaymentGateway.
type MockDepositPaymentGatewayMockRecorder struct {
	mock *MockDepositPaymentGateway
}

// NewMockDepositPaymentGateway creates a new mock instance.
func NewMockDepositPaymentGateway(ctrl *gomock.Controller) *MockDepositPaymentGateway {
	mock := &MockDepositPaymentGateway{ctrl: ctrl}
	mock.recorder = &MockDepositPaymentGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepositPaymentGateway) EXPECT() *MockDepositPaymentGatewayMockRecorder {
	return m.recorder
}

// Deposit mocks base method.
func (m *MockDepositPaymentGateway) Deposit(req shared.Request) (*shared.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", req)
	ret0, _ := ret[0].(*shared.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deposit indicates an expected call of Deposit.
func (mr *MockDepositPaymentGatewayMockRecorder) Deposit(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockDepositPaymentGateway)(nil).Deposit), req)
}
