// Code generated by MockGen. DO NOT EDIT.
// Source: internal/status/common/service.go

// Package status is a generated GoMock package.
package common

import (
	reflect "reflect"
	shared "zota-dev-challenge/internal/status/shared"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// CheckStatus mocks base method.
func (m *MockServiceInterface) CheckStatus(req *shared.ClientRequest) (*shared.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStatus", req)
	ret0, _ := ret[0].(*shared.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckStatus indicates an expected call of CheckStatus.
func (mr *MockServiceInterfaceMockRecorder) CheckStatus(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStatus", reflect.TypeOf((*MockServiceInterface)(nil).CheckStatus), req)
}
